"""model analysis added to init

Revision ID: 1655c4fc751d
Revises: 895b2c26a0da
Create Date: 2026-01-27 10:53:03.175140

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1655c4fc751d'
down_revision: Union[str, Sequence[str], None] = '895b2c26a0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_analysis_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_hash', sa.String(), nullable=False),
    sa.Column('analysis_type', sa.String(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('reference_url', sa.Text(), nullable=True),
    sa.Column('current_url', sa.Text(), nullable=True),
    sa.Column('model_url', sa.Text(), nullable=True),
    sa.Column('target_column', sa.String(), nullable=True),
    sa.Column('sensitive_feature', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('discover_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['discover_id'], ['discover.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_analysis_requests_discover_id'), 'model_analysis_requests', ['discover_id'], unique=False)
    op.create_index(op.f('ix_model_analysis_requests_request_hash'), 'model_analysis_requests', ['request_hash'], unique=True)
    op.create_table('model_analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('analysis_type', sa.String(), nullable=False),
    sa.Column('overall_status', sa.String(), nullable=True),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('fairness_metrics', sa.JSON(), nullable=True),
    sa.Column('feature_importance', sa.JSON(), nullable=True),
    sa.Column('threshold_evaluations', sa.JSON(), nullable=True),
    sa.Column('llm_analysis', sa.JSON(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('discover_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['discover_id'], ['discover.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['model_analysis_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_analysis_results_discover_id'), 'model_analysis_results', ['discover_id'], unique=False)
    op.create_index(op.f('ix_model_analysis_results_request_id'), 'model_analysis_results', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_analysis_results_request_id'), table_name='model_analysis_results')
    op.drop_index(op.f('ix_model_analysis_results_discover_id'), table_name='model_analysis_results')
    op.drop_table('model_analysis_results')
    op.drop_index(op.f('ix_model_analysis_requests_request_hash'), table_name='model_analysis_requests')
    op.drop_index(op.f('ix_model_analysis_requests_discover_id'), table_name='model_analysis_requests')
    op.drop_table('model_analysis_requests')
    # ### end Alembic commands ###
