"""analysis type added

Revision ID: 5d5baa6514c3
Revises: ad96297e16d1
Create Date: 2026-01-24 10:43:40.271218

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5d5baa6514c3'
down_revision: Union[str, Sequence[str], None] = 'ad96297e16d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discover', sa.Column('analysis_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discover', 'analysis_type')
    # ### end Alembic commands ###
