"""model analysis tables

Revision ID: 895b2c26a0da
Revises: 5d5baa6514c3
Create Date: 2026-01-27 10:39:52.298244

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '895b2c26a0da'
down_revision: Union[str, Sequence[str], None] = '5d5baa6514c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discover', 'analysis_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('discover', 'project_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('discover', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('discover', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_discover_analysis_type'), 'discover', ['analysis_type'], unique=False)
    op.create_unique_constraint('uq_discover_tenant_project', 'discover', ['tenant_id', 'project_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_discover_tenant_project', 'discover', type_='unique')
    op.drop_index(op.f('ix_discover_analysis_type'), table_name='discover')
    op.alter_column('discover', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('discover', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('discover', 'project_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('discover', 'analysis_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
