"""add user_id and tenant_id to model_analysis_results

Revision ID: a67fcd781561
Revises: f25508c149e1
Create Date: 2026-01-27 18:54:39.458932

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a67fcd781561'
down_revision: Union[str, Sequence[str], None] = 'f25508c149e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_analysis_results', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('model_analysis_results', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_model_analysis_results_tenant_id'), 'model_analysis_results', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_model_analysis_results_user_id'), 'model_analysis_results', ['user_id'], unique=False)
    op.create_foreign_key(None, 'model_analysis_results', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'model_analysis_results', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model_analysis_results', type_='foreignkey')
    op.drop_constraint(None, 'model_analysis_results', type_='foreignkey')
    op.drop_index(op.f('ix_model_analysis_results_user_id'), table_name='model_analysis_results')
    op.drop_index(op.f('ix_model_analysis_results_tenant_id'), table_name='model_analysis_results')
    op.drop_column('model_analysis_results', 'tenant_id')
    op.drop_column('model_analysis_results', 'user_id')
    # ### end Alembic commands ###
