"""relationship updated

Revision ID: f25508c149e1
Revises: 1655c4fc751d
Create Date: 2026-01-27 18:44:31.602967

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'f25508c149e1'
down_revision: Union[str, Sequence[str], None] = '1655c4fc751d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
